---
title: "AS_DisEco_Fall2024"
author: "Amatallah Saulawa"
format: html
editor: visual
---

**Integrating Code and Text**

Find area of a circle with radius 5 cm.

Formula: ¶ \* r\^2

where r is the radius.

```{r}
# Function to calculate the area of a circle
area_of_circle <- function(radius) {
  area <- pi * radius^2
  return(area)
}
radius <- 5 # from the example
circle_area <- area_of_circle(radius)
cat("The area of the circle with radius", radius, "is", circle_area, "\n")
```

**Inserting an Image in Quarto Document**

<https://github.com/asaulawa/WILDin5200/blob/5574b59c372cc285c5062a312435f24f92074f04/Intro/EpiTriad.png>

Disease ecology looks at the relationship between hosts, environment, and pathogens.

[***Worksheet 2 & 3***]{.underline}

**1) Find the sample size necessary to detect a disease at or above 5% prevalence in a herd of 5000 deer. The desired level of confidence is 95%.**

59

**2) Using the hypergeometric distribution, compare the sample size requirements for the following scenarios:\
a) 95% confidence in detecting a disease at 1% prevalence in a large population\
b) 99% confidence in detecting a disease at 2% prevalence in a large population**

The sample size (299) for 95% confidence would be higher than the sample size (229) needed for 99% confidence.

**3) You sample 300 deer from a high fenced facility that has a herd of 4000. None of the 300 have antibodies against Epizootic Hemorrhagic Disease. Based on this finding, you are 95% confident that the prevalence of exposure to EHD in this facility is \_\_\_\_\_ (\<, =,\>) \_\_\_\_%**\
less than 1%

**4) An outbreak of ‘Lame disease’ has been reported in wild turkey populations of Alabama. Turkeys from three counties were sampled for lameness (Lee, Chambers and Russell counties).\
a) Analyze the sample data to determine prevalence of lameness in each county. Provide confidence interval for prevalence using Sterne’s method.**

| County           | Prevalence | 95% CI       |
|------------------|------------|--------------|
| Lee county:      | 20.0%      | (14%, 27%)   |
| Chambers county: | 26.7%      | (13%, 45%)   |
| Russell county   | 3.1%       | (0.9%, 8.7%) |

**\
b) Compare prevalences using Fisher’s exact test.**

Russell has 3.1% prevalence, Lee 20%, and Chambers 26.7%.

The two-sided p-value is \<0.001

P value is less than 0.05, so the difference is statistically significant.\

**5) Jane was studying the spread of Pink Spot Disease (PSD) in a pond that had 60 fish.\
She introduced an infectious fish in the pond on day 0. Her observations are as follows:\
Day 1: 3 fish infected\
Day 2: 4 fish infected\
Day 3: 7 fish infected\
Day 4: 11 fish infected\
Day 5: 20 fish infected\
Note that there is no disease-related mortality. The observations denote all infected fish in the pond (including previously infected fish).**

| Day | Susceptible | Total Infected | New Infections | Incidence | Prevalence |
|-----|-------------|----------------|----------------|-----------|------------|
| 1   | 60          | 3              | 3              | 3/60      | 3/60       |
| 2   | 57          | 4              | 1              | 1/57      | 4/60       |
| 3   | 56          | 7              | 3              | 3/56      | 7/60       |
| 4   | 53          | 11             | 4              | 4/53      | 11/60      |
| 5   | 49          | 20             | 9              | 9/49      | 20/60      |

**\
a) Find incidence on day 1, day 2 and day 5. Write the unit for incidence.**

Day 1: 0.05 cases per fish-day

Day 2: 0.018 cases per fish-day

Day 5: 0.183 cases per fish-day**\
b) What is the prevalence of PSD on day 3 and day 5?**

Day 3: 7/60; prevalence rate 12%

Day 5: 20/60; prevalence rate 33%**\
c) On which day is the prevalence same as the incidence (except the units)?**\
Day 1

***Worksheet 4***

*Explain how disease models can contribute to better wildlife disease management strategies. Reflect on the limitations of disease models, including data uncertainty and ecological complexity, and suggest how models can be used alongside **other tools** to improve wildlife disease management outcomes.*

Disease models deepen our understanding of disease processes by allowing us to represent wildlife disease processes and interactions among different components of ecosystems. These representations can help tailor disease management strategies. Since ecosystems and host-agent interactions in the real world are variable, disease modeling can allow us to test and understand the outcomes of different host-agent interaction paradigms. Models can supplement understanding of disease spread and development by testing out different hypotheses regarding their spread that are grounded in either empirical or anecdotal data. For example, if an infectious agent is adaptable to different conditions and has previously shifted hosts, a probabilistic disease model could test to see how the agent would affect wildlife populations if it adapts to infect their population. Additionally, such a model could also be used to test the efficacy of different management strategies and risk mitigation measures in responding to disease outbreaks. The result would be better decision-making and a deeper understanding of a specific environment using data insights. 

Since models are representations of data fed by humans, they are limited by the quality of the available data. Still, they can be helpful in modeling different disease spreads and identifying the limitations of current data. Where there are limitations, different approaches, such as active surveillance or wastewater surveillance, can be used to improve data quality as needed. These surveillance methods, along with low-cost methods such as rumor surveillance, could be used to inform understanding of a disease’s spread and tailor the type of models that are tested. Other factors such as scientific research, a disease’s historical spread and trends, and past experience managing a specific population could also inform model choice and the type of variables that are represented in the model. If it is not feasible to supplement existing data through other data collection methods due to time constraints, then wildlife managers can make critical decisions using predictions based on representations of their existing data. Even with high-quality data, models will always have limitations as they will never be able to represent the complexity of the real world. However, they can help us make better choices and determine the best strategies for addressing a disease.  

Disease models can be used to represent the complexity of different ecosystems by focusing on the most important data or interactions the model needs to capture. Like with models that have incomplete data, these models may not represent all of the nuances present in an ecosystem. To address this, wildlife managers can create multiple models that each capture the single most important aspects of the host, agent, and environmental interactions instead of trying to capture all the different interactions that take place in an ecosystem within a single model. Doing so would allow the model to be pared down and simple to understand while still reflecting the complexity of the wildlife ecosystem.

**Exam 1 Question Makeup**

Bonus Question:

12. The Dutch harbor seal population is estimated to be around 5400 with \~50% adults. Seals are susceptible to phocine distemper virus (PDV), but an estimated 40% of the adults in this population are immune to PDV by virtue of prior natural infection. How many seals in this population should be vaccinated in order to achieve herd immunity sufficient to prevent an outbreak of PDV in this population if the R0 is estimated to be \~3. Assume that all the adult seals that have survived prior PDV infection are tagged and hence identifiable.

1-1/3=\~67%. There needs to be \~67%, vaccination coverage to achieve herd immunity in fully susceptible population

.67\*5400=3618 vaccines need for entire population if fully susceptible.

However, there are 2700 adults (5400/2=2700), with 1080 (.4\*2700) being immune already.

Thus the number of susceptible seals is actually 3618-1080= 2538.

Thus, 2538 harbor seals need to be vaccinated in order to achieve herd immunity in this population.
