---
title: "AS_DisEco_Fall2024"
author: "Amatallah Saulawa"
format: html
editor: visual
---

**Integrating Code and Text**

Find area of a circle with radius 5 cm.

Formula: ¶ \* r\^2

where r is the radius.

```{r}
# Function to calculate the area of a circle
area_of_circle <- function(radius) {
  area <- pi * radius^2
  return(area)
}
radius <- 5 # from the example
circle_area <- area_of_circle(radius)
cat("The area of the circle with radius", radius, "is", circle_area, "\n")
```

**Inserting an Image in Quarto Document**

<https://github.com/asaulawa/WILDin5200/blob/5574b59c372cc285c5062a312435f24f92074f04/Intro/EpiTriad.png>

Disease ecology looks at the relationship between hosts, environment, and pathogens.

[***Worksheet 2 & 3***]{.underline}

**1) Find the sample size necessary to detect a disease at or above 5% prevalence in a herd of 5000 deer. The desired level of confidence is 95%.**

59

**2) Using the hypergeometric distribution, compare the sample size requirements for the following scenarios:\
a) 95% confidence in detecting a disease at 1% prevalence in a large population\
b) 99% confidence in detecting a disease at 2% prevalence in a large population**

The sample size (299) for 95% confidence would be higher than the sample size (229) needed for 99% confidence.

**3) You sample 300 deer from a high fenced facility that has a herd of 4000. None of the 300 have antibodies against Epizootic Hemorrhagic Disease. Based on this finding, you are 95% confident that the prevalence of exposure to EHD in this facility is \_\_\_\_\_ (\<, =,\>) \_\_\_\_%**\
less than 1%

**4) An outbreak of ‘Lame disease’ has been reported in wild turkey populations of Alabama. Turkeys from three counties were sampled for lameness (Lee, Chambers and Russell counties).\
a) Analyze the sample data to determine prevalence of lameness in each county. Provide confidence interval for prevalence using Sterne’s method.**

| County           | Prevalence | 95% CI       |
|------------------|------------|--------------|
| Lee county:      | 20.0%      | (14%, 27%)   |
| Chambers county: | 26.7%      | (13%, 45%)   |
| Russell county   | 3.1%       | (0.9%, 8.7%) |

**\
b) Compare prevalences using Fisher’s exact test.**

Russell has 3.1% prevalence, Lee 20%, and Chambers 26.7%.

The two-sided p-value is \<0.001

P value is less than 0.05, so the difference is statistically significant.\

**5) Jane was studying the spread of Pink Spot Disease (PSD) in a pond that had 60 fish.\
She introduced an infectious fish in the pond on day 0. Her observations are as follows:\
Day 1: 3 fish infected\
Day 2: 4 fish infected\
Day 3: 7 fish infected\
Day 4: 11 fish infected\
Day 5: 20 fish infected\
Note that there is no disease-related mortality. The observations denote all infected fish in the pond (including previously infected fish).**

| Day | Susceptible | Total Infected | New Infections | Incidence | Prevalence |
|-----|-------------|----------------|----------------|-----------|------------|
| 1   | 60          | 3              | 3              | 3/60      | 3/60       |
| 2   | 57          | 4              | 1              | 1/57      | 4/60       |
| 3   | 56          | 7              | 3              | 3/56      | 7/60       |
| 4   | 53          | 11             | 4              | 4/53      | 11/60      |
| 5   | 49          | 20             | 9              | 9/49      | 20/60      |

**\
a) Find incidence on day 1, day 2 and day 5. Write the unit for incidence.**

Day 1: 3 cases per fish-day

Day 2: 1 cases per fish-day

Day 5: 9 cases per fish-day**\
b) What is the prevalence of PSD on day 3 and day 5?**

Day 3: 7/60; prevalence rate 12%

Day 5: 20/60; prevalence rate 33%**\
c) On which day is the prevalence same as the incidence (except the units)?**\
Day 1
